defaults: &defaults
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  url: <%= ENV["MYSQL_URL"] %>

development:
  <<: *defaults
  database: <%= ENV["MYSQL_DATABASE"] %>_development

test:
  <<: *defaults
  database: <%= ENV["MYSQL_DATABASE"] %>_test

staging:
  <<: *defaults
  database: <%= ENV["MYSQL_DATABASE"] %>_staging

production:
  <<: *defaults
  database: <%= ENV["MYSQL_DATABASE"] %>_production
